name: Build and Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-upload:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd bot
          GOARCH=amd64 GOOS=linux go build -o bootstrap main.go

      - name: Zip
        run: |
          cd bot
          zip lambda_function.zip bootstrap

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.PIPELINE_EXEC_ROLE_ARN }}
          role-session-name: GitHubActions
          role-duration-seconds: 3600

      - name: Upload to S3
        run: aws s3 cp bot/lambda_function.zip s3://${{ vars.S3_LAMBDA_BUCKET }}/lambda_function.zip